### ISSUE TITLE
/sbin/get_available_templates: command not found

### ISSUE THREAD

**Issue by sayghteight** [FlamesRunner/natCP#9]
this file is nowhere to be found

**Comment by FlamesRunner** [comment]
The contents of the script should be: 

    #!/bin/bash
    ls /vz/template/cache

However, it's not necessary to put it as its own file, and if you'd like, I'll apply the Hacktoberfest label and allow you to change it.

**Comment by sayghteight** [comment]
I have created the file in my sbin directory

With the following code

#! / bin / bash ls / vz / template / cache

I've saved it as get_available_templates.

But it's still the same.

**Comment by FlamesRunner** [comment]
Did you set the appropriate permissions on the file? They should be 755.

**Comment by sayghteight** [comment]
Fixed, i go upload in my repository

**Comment by FlamesRunner** [comment]
If everything's good, do close the issue. Thanks!
